services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
      - ./frontend/dist:/usr/share/nginx/html  
    ports:
      - "80:80"
      - "443:443"
    networks:
      - promisenet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /var/www/certbot:/var/www/certbot
      - ./certs:/etc/letsencrypt
      - ./certs/log:/var/log/letsencrypt
      - ./certs/lib:/var/lib/letsencrypt
    entrypoint: >
      sh -c 'trap exit TERM;
             while :; do
               certbot renew --webroot -w /var/www/certbot \
                 --config-dir /etc/letsencrypt \
                 --logs-dir /var/log/letsencrypt \
                 --work-dir /var/lib/letsencrypt \
                 --quiet;
               sleep 12h & wait $${!};
             done'
    networks:
      - promisenet

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: root
    ports:
      - "8081:8081"
    command: --httpPort=8081
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - promisenet
    environment:
      - JENKINS_OPTS=--httpPort=8081 --httpListenAddress=0.0.0.0
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-time-zone=UTC"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - promisenet

  redis:
    image: redis:7.2-alpine
    container_name: demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - promisenet
  
  spring-api:
    build:
      context: ./backend-spring
    container_name: spring-api
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&rewriteBatchedStatements=true
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - promisenet

  mediasoup:
    build:
      context: ./mediasoup-demo/server
      dockerfile: Dockerfile
    container_name: mediasoup
    ports:
      - "3002:3000"
    networks:
      - promisenet
    volumes:
    - ./certs:/home/ubuntu/certs

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    restart: always
    networks:
      - promisenet

volumes:
  mysql_data:
  redis-data:

networks:
  promisenet:
    driver: bridge

